# -*- coding: utf-8 -*-
"""Telecom ML Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kYY6zYuyZ7UMZgQ-Pp8r-Ksa54OALqs8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, ExtraTreesClassifier
import xgboost as xgb
import lightgbm as lgb
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, recall_score
from sklearn.model_selection import GridSearchCV

df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

df.info()

df = df.drop_duplicates()
df = df.dropna()

for col in df.select_dtypes(include='object').columns:
    if col != 'Churn':
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])

df['Churn'] = df['Churn'].map({'No': 0, 'Yes': 1})

df = df.drop('customerID', axis=1)

sns.countplot(x='Churn', data=df)
plt.show()
plt.figure(figsize=(12,8))
sns.heatmap(df.corr(), annot=True, fmt='.2f')
plt.show()

X = df.drop('Churn', axis=1)
y = df['Churn']

df.head()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "XGBoost": xgb.XGBClassifier(eval_metric='logloss', random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "SVM": SVC(kernel='rbf', probability=True, random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=100, random_state=42),
    "AdaBoost": AdaBoostClassifier(n_estimators=100, random_state=42),
    "Extra Trees": ExtraTreesClassifier(n_estimators=100, random_state=42),
    "LightGBM": lgb.LGBMClassifier(n_estimators=100, random_state=42)}
results = []

for name, model in models.items():
    model.fit(X_train_sm, y_train_sm)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    print(f"\n--- {name} ---")
    print("Accuracy:", round(acc, 4))
    print("Classification Report:\n", classification_report(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("Recall:", round(recall, 4))
    results.append([name, acc, recall])

results_df = pd.DataFrame(results, columns=['Model', 'Accuracy', 'Recall']).sort_values(by='Accuracy', ascending=False)
print("\n=== Model Accuracy Comparison ===")
print(results_df)

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostClassifier
param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 1]
}
grid = GridSearchCV(
    AdaBoostClassifier(random_state=42),
    param_grid,
    cv=3,
    scoring='recall',
    n_jobs=-1
)
grid.fit(X_train_sm, y_train_sm)
print("Best Parameters:", grid.best_params_)

best_model = grid.best_estimator_
y_pred = best_model.predict(X_test)
print("\n=== FINAL MODEL ===")
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_sm, y_train_sm)
importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_})
importance = importance.sort_values(by='Importance', ascending=False)
print("\nTop 10 Important Features:")
print(importance.head(10))
plt.figure(figsize=(10,6))
sns.barplot(x='Importance', y='Feature', data=importance.head(10))
plt.title("Top 10 Features Influencing Churn")
plt.show()

decode_maps = {

    'Churn': {0:'No', 1:'Yes'},
    'gender': {0:'Female', 1:'Male'},
    'Partner': {0:'No', 1:'Yes'},
    'Dependents': {0:'No', 1:'Yes'},
    'PhoneService': {0:'No', 1:'Yes'},
    'MultipleLines': {0:'No', 1:'Yes', 2:'No phone service'},
    'InternetService': {0:'DSL', 1:'Fiber optic', 2:'No'},
    'OnlineSecurity': {0:'No', 1:'Yes', 2:'No internet service'},
    'OnlineBackup': {0:'No', 1:'Yes', 2:'No internet service'},
    'DeviceProtection': {0:'No', 1:'Yes', 2:'No internet service'},
    'TechSupport': {0:'No', 1:'Yes', 2:'No internet service'},
    'StreamingTV': {0:'No', 1:'Yes', 2:'No internet service'},
    'StreamingMovies': {0:'No', 1:'Yes', 2:'No internet service'},
    'Contract': {0:'Month-to-month', 1:'One year', 2:'Two year'},
    'PaperlessBilling': {0:'No', 1:'Yes'},
    'PaymentMethod': {0:'Electronic check', 1:'Mailed check', 2:'Bank transfer (automatic)', 3:'Credit card (automatic)'}
}

for col, mapping in decode_maps.items():
    if col in df.columns:
        df[col] = df[col].map(mapping)

df.to_csv('churn_dashboard_data_decoded.csv', index=False)
print("Decoded CSV exported: churn_dashboard_data_decoded.csv")

from google.colab import files
files.download('churn_dashboard_data_decoded.csv')